import Head from "next/head";
import React from "react";

const HeadApp = () => (
  <Head>
    <title>Country list app</title>
    <meta
      name="Country list app"
      content="Generated by Ángel Bernardo Lupiáñez"
    />
    Country List
  </Head>
);

export default HeadApp;
