import Head from "next/head";
import React from "react";

const HeadApp = () => (
  <Head>
    <title>Playtomic app</title>
    <meta
      name="app requested by Playtomic"
      content="Generated by Ángel Bernardo Lupiáñez"
    />
    <link rel="icon" href="/playtomicIcon.ico" />
  </Head>
);

export default HeadApp;
